// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXv8gZCcsG6GLvuCPVNqW_emRs6OF8m8g',
    appId: '1:60151611391:web:3f2cd0bc4bd54b8e0af1ca',
    messagingSenderId: '60151611391',
    projectId: 'aridnik-share-63b24',
    authDomain: 'aridnik-share-63b24.firebaseapp.com',
    storageBucket: 'aridnik-share-63b24.appspot.com',
    measurementId: 'G-J63F7ZV3W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGq5N0nUuxMzUkLzqBduB30OMwog-u0o',
    appId: '1:60151611391:android:ff0b29e816eb3f180af1ca',
    messagingSenderId: '60151611391',
    projectId: 'aridnik-share-63b24',
    storageBucket: 'aridnik-share-63b24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMDyCyxVusf1PB6mB_ZjCKA4iPwIorRg',
    appId: '1:60151611391:ios:43f2edf9343999cb0af1ca',
    messagingSenderId: '60151611391',
    projectId: 'aridnik-share-63b24',
    storageBucket: 'aridnik-share-63b24.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKMDyCyxVusf1PB6mB_ZjCKA4iPwIorRg',
    appId: '1:60151611391:ios:7cb97e89d46728df0af1ca',
    messagingSenderId: '60151611391',
    projectId: 'aridnik-share-63b24',
    storageBucket: 'aridnik-share-63b24.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
